/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.Application;
import model.VitalSignHistory;

/**
 *
 * @author shalomdaniel
 */
public class CreateJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form CreateJPanel
     */
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application = application;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldObservationTemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fieldObservationID1 = new javax.swing.JTextField();
        fieldObservationBP1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AddBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Create a VItal Sign");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        fieldObservationTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationTempActionPerformed(evt);
            }
        });
        add(fieldObservationTemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 110, -1));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, 10));

        jLabel3.setText("Blood Pressure");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        fieldObservationID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationID1ActionPerformed(evt);
            }
        });
        add(fieldObservationID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, -1));

        fieldObservationBP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldObservationBP1ActionPerformed(evt);
            }
        });
        add(fieldObservationBP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, -1));

        jLabel4.setText("Temperature");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 90));

        AddBtn.setText("Add Observation");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldObservationTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationTempActionPerformed

    private void fieldObservationID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationID1ActionPerformed

    private void fieldObservationBP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldObservationBP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldObservationBP1ActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        
        VitalSignHistory history = this.application.getHistory();
        
        String id = fieldObservationID1.getText();
        String temp = fieldObservationTemp.getText();
        String bloodPressure = fieldObservationBP1.getText();
        
        
        history.createObservation(Integer.valueOf(id), Double.valueOf(bloodPressure), Double.valueOf(temp));
        
        JOptionPane.showMessageDialog(null, "Successfully Added observation to Vital Sign History");
        
    }//GEN-LAST:event_AddBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField fieldObservationBP1;
    private javax.swing.JTextField fieldObservationID1;
    private javax.swing.JTextField fieldObservationTemp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
