/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Model.Address;
import Model.Contact;
import Model.Person;

/**
 *
 * @author shalomdaniel
 */
public class Frontend extends javax.swing.JFrame {

    /**
     * Creates new form Frontend
     */
    
    Person person;
    
    public Frontend() {
        initComponents();
        
        this.person = new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        create_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldColgName = new javax.swing.JTextField();
        fieldNUID = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        fieldStreet = new javax.swing.JTextField();
        fieldApt = new javax.swing.JTextField();
        fieldCity = new javax.swing.JTextField();
        fieldState = new javax.swing.JTextField();
        fieldZip = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fieldPermStreet = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fieldPermApt = new javax.swing.JTextField();
        fieldPermCity = new javax.swing.JTextField();
        fieldPermState = new javax.swing.JTextField();
        fieldPermZip = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fieldOfficePhone = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fieldOfficeEmail = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        view_panel = new javax.swing.JPanel();
        viewColgName = new javax.swing.JLabel();
        viewEmail = new javax.swing.JLabel();
        viewNUID = new javax.swing.JLabel();
        viewPhone = new javax.swing.JLabel();
        viewApt = new javax.swing.JLabel();
        viewStreet = new javax.swing.JLabel();
        viewCity = new javax.swing.JLabel();
        viewState = new javax.swing.JLabel();
        viewLastName = new javax.swing.JLabel();
        viewFirstName = new javax.swing.JLabel();
        viewZipcode = new javax.swing.JLabel();
        viewOfficePhone = new javax.swing.JLabel();
        viewOfficeEmail = new javax.swing.JLabel();
        viewPermStreet = new javax.swing.JLabel();
        viewPermApt = new javax.swing.JLabel();
        viewPermCity = new javax.swing.JLabel();
        viewPermState = new javax.swing.JLabel();
        viewPermZip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("First Name");

        jLabel2.setText("Last Name");

        jLabel3.setText("College Name");

        jLabel4.setText("NUID");

        jLabel5.setText("Personal Phone Number  (+1)");

        jLabel6.setText("Personal Email ID");

        jLabel7.setText("Street Name");

        jLabel8.setText("Apt.No");

        jLabel9.setText("City");

        jLabel10.setText("State");

        jLabel11.setText("Zip Code");

        fieldApt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAptActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Oriya Sangam MN", 3, 18)); // NOI18N
        jLabel12.setText("College Address");

        jLabel13.setFont(new java.awt.Font("Oriya Sangam MN", 3, 18)); // NOI18N
        jLabel13.setText("Permanent Address");

        jLabel14.setText("Street Name");

        jLabel15.setText("Apt.No");

        jLabel16.setText("City");

        jLabel17.setText("State");

        jLabel18.setText("Zip Code");

        jLabel19.setText("Office Phone Number (+1) ");

        fieldOfficePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOfficePhoneActionPerformed(evt);
            }
        });

        jLabel20.setText("Office Email ID");

        jLabel21.setFont(new java.awt.Font("Apple Chancery", 1, 24)); // NOI18N
        jLabel21.setText("Student Husky Card Details ");

        javax.swing.GroupLayout create_panelLayout = new javax.swing.GroupLayout(create_panel);
        create_panel.setLayout(create_panelLayout);
        create_panelLayout.setHorizontalGroup(
            create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(create_panelLayout.createSequentialGroup()
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(create_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(create_panelLayout.createSequentialGroup()
                                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(create_panelLayout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel4))
                                    .addGroup(create_panelLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel6))))
                                    .addComponent(jLabel12)
                                    .addGroup(create_panelLayout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel3))
                                    .addGroup(create_panelLayout.createSequentialGroup()
                                        .addGap(85, 85, 85)
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))))
                                .addGap(18, 18, 18)
                                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldColgName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fieldOfficePhone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(fieldPhone, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                            .addComponent(fieldEmail, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(create_panelLayout.createSequentialGroup()
                                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(create_panelLayout.createSequentialGroup()
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(6, 6, 6)
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(fieldStreet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                                .addComponent(fieldApt, javax.swing.GroupLayout.Alignment.LEADING)))
                                        .addGap(41, 41, 41)
                                        .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldPermState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(fieldPermCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPermApt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPermStreet, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPermZip)))))
                    .addGroup(create_panelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        create_panelLayout.setVerticalGroup(
            create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(create_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(7, 7, 7)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(create_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(create_panelLayout.createSequentialGroup()
                        .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldColgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldOfficePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(fieldOfficeEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(fieldPermStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fieldApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(fieldPermApt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(fieldPermCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(fieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(fieldPermState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(create_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(fieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(fieldPermZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(create_panel);

        view_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewColgName.setText("jLabel12");
        view_panel.add(viewColgName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        viewEmail.setText("jLabel13");
        view_panel.add(viewEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        viewNUID.setText("jLabel14");
        view_panel.add(viewNUID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, -1, -1));

        viewPhone.setText("jLabel15");
        view_panel.add(viewPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 57, -1, -1));

        viewApt.setText("jLabel16");
        view_panel.add(viewApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        viewStreet.setText("jLabel17");
        view_panel.add(viewStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        viewCity.setText("jLabel18");
        view_panel.add(viewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        viewState.setText("jLabel19");
        view_panel.add(viewState, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));

        viewLastName.setText("jLabel20");
        view_panel.add(viewLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        viewFirstName.setText("jLabel21");
        view_panel.add(viewFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 6, -1, -1));

        viewZipcode.setText("jLabel22");
        view_panel.add(viewZipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 20));

        viewOfficePhone.setText("jLabel22");
        view_panel.add(viewOfficePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 91, -1, -1));

        viewOfficeEmail.setText("jLabel23");
        view_panel.add(viewOfficeEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        viewPermStreet.setText("jLabel22");
        view_panel.add(viewPermStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 135, -1, -1));

        viewPermApt.setText("jLabel23");
        view_panel.add(viewPermApt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        viewPermCity.setText("jLabel24");
        view_panel.add(viewPermCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 169, -1, -1));

        viewPermState.setText("jLabel25");
        view_panel.add(viewPermState, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        viewPermZip.setText("jLabel26");
        view_panel.add(viewPermZip, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        jSplitPane1.setRightComponent(view_panel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String firstname = fieldFirstName.getText();
        String lastname = fieldLastName.getText();   
        String colgName = fieldColgName.getText();
        String nuid = fieldNUID.getText();
        String colg_street = fieldStreet.getText();
        String perm_street = fieldPermStreet.getText();
        String colg_apt_no = fieldApt.getText();
        String perm_apt_no = fieldPermApt.getText();
        String colg_city = fieldCity.getText();
        String perm_city = fieldPermCity.getText();
        String colg_state = fieldState.getText();
        String perm_state = fieldPermState.getText();
        String email = fieldEmail.getText();
        String officeEmail = fieldOfficeEmail.getText();
        long localPhone = Long.valueOf(fieldPhone.getText());
        long officePhone = Long.valueOf(fieldOfficePhone.getText());
        int zip = Integer.valueOf(fieldZip.getText());
        int permZip = Integer.valueOf(fieldPermZip.getText());
        
      
        Address colg_address = this.person.getCollege_address();
        Address perm_address = this.person.getPermanentAddress();

        Contact personalContact = this.person.getPersonalContact();
        Contact officeContact = this.person.getOfficeContact();
        
        this.person.setFirstname(firstname);
        this.person.setLastname(lastname);
        this.person.setCollege_name(colgName);
        this.person.setNuid(nuid);

        colg_address.setStreet(colg_street);
        colg_address.setApt_no(colg_apt_no);
        colg_address.setCity(colg_city);
        colg_address.setState(colg_state);
        colg_address.setZipcode(zip);
        
        perm_address.setStreet(perm_street);
        perm_address.setApt_no(perm_apt_no);
        perm_address.setCity(perm_city);
        perm_address.setState(perm_state);
        perm_address.setZipcode(permZip);
        
        personalContact.setEmail(email);
        personalContact.setPhone_number(localPhone);
        
        officeContact.setEmail(officeEmail);
        officeContact.setPhone_number(officePhone);
        
        display();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fieldAptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAptActionPerformed

    private void fieldOfficePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOfficePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOfficePhoneActionPerformed

    private void display() {
        viewFirstName.setText(this.person.getFirstname());
        viewLastName.setText(this.person.getLastname());
        viewColgName.setText(this.person.getCollege_name());
        viewNUID.setText(this.person.getNuid());

        viewStreet.setText(this.person.getCollege_address().getStreet());
        viewApt.setText(this.person.getCollege_address().getApt_no());
        viewCity.setText(this.person.getCollege_address().getCity());
        viewState.setText(this.person.getCollege_address().getState());
        viewZipcode.setText(String.valueOf(this.person.getCollege_address().getZipcode()));
        
        viewPermStreet.setText(this.person.getPermanentAddress().getStreet());
        viewPermApt.setText(this.person.getPermanentAddress().getApt_no());
        viewPermCity.setText(this.person.getPermanentAddress().getCity());
        viewPermState.setText(this.person.getPermanentAddress().getState());
        viewPermZip.setText(String.valueOf(this.person.getPermanentAddress().getZipcode()));
        
        viewPhone.setText(String.valueOf(this.person.getPersonalContact().getPhone_number()));
        viewOfficePhone.setText(String.valueOf(this.person.getOfficeContact().getPhone_number()));       
        viewEmail.setText(this.person.getPersonalContact().getEmail());
        viewOfficeEmail.setText(this.person.getOfficeContact().getEmail());

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frontend.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frontend().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel create_panel;
    private javax.swing.JTextField fieldApt;
    private javax.swing.JTextField fieldCity;
    private javax.swing.JTextField fieldColgName;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNUID;
    private javax.swing.JTextField fieldOfficeEmail;
    private javax.swing.JTextField fieldOfficePhone;
    private javax.swing.JTextField fieldPermApt;
    private javax.swing.JTextField fieldPermCity;
    private javax.swing.JTextField fieldPermState;
    private javax.swing.JTextField fieldPermStreet;
    private javax.swing.JTextField fieldPermZip;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldState;
    private javax.swing.JTextField fieldStreet;
    private javax.swing.JTextField fieldZip;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel viewApt;
    private javax.swing.JLabel viewCity;
    private javax.swing.JLabel viewColgName;
    private javax.swing.JLabel viewEmail;
    private javax.swing.JLabel viewFirstName;
    private javax.swing.JLabel viewLastName;
    private javax.swing.JLabel viewNUID;
    private javax.swing.JLabel viewOfficeEmail;
    private javax.swing.JLabel viewOfficePhone;
    private javax.swing.JLabel viewPermApt;
    private javax.swing.JLabel viewPermCity;
    private javax.swing.JLabel viewPermState;
    private javax.swing.JLabel viewPermStreet;
    private javax.swing.JLabel viewPermZip;
    private javax.swing.JLabel viewPhone;
    private javax.swing.JLabel viewState;
    private javax.swing.JLabel viewStreet;
    private javax.swing.JLabel viewZipcode;
    private javax.swing.JPanel view_panel;
    // End of variables declaration//GEN-END:variables
}
