/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import model.Application;
import model.Medicine;
import model.Observation;

/**
 *
 * @author shalomdaniel
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {

    private Application application;

    /**
     * Creates new form MedicineAssignJPanel
     */
    public MedicineAssignJPanel() {
        initComponents();
    }

    MedicineAssignJPanel(Application application) {
        initComponents();
        
        this.application = application;
        
        populateDropdowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MedicineBox = new javax.swing.JComboBox();
        ObservationBox = new javax.swing.JComboBox();
        assignBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        add(MedicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 137, 170, 70));

        ObservationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ObservationBoxItemStateChanged(evt);
            }
        });
        add(ObservationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 200, -1));

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        // TODO add your handling code here:
        
        Observation o = (Observation) ObservationBox.getSelectedItem();
        Medicine m = (Medicine) MedicineBox.getSelectedItem();
        o.setMed_assignment(m);
        
    }//GEN-LAST:event_assignBtnActionPerformed

    private void ObservationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ObservationBoxItemStateChanged
        // TODO add your handling code here:
//        
//        Observation o : (Observation) ObservationBox.getSelectedItem();
//        
//        if(o.getMed_assignment()!= null){
//            j
//        }
        
    }//GEN-LAST:event_ObservationBoxItemStateChanged

    public void populateDropdowns(){
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        
        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o : observations){
            ObservationBox.addItem(o);
        }
        
        for(Medicine m : medicines){
            MedicineBox.addItem(m);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox MedicineBox;
    private javax.swing.JComboBox ObservationBox;
    private javax.swing.JButton assignBtn;
    // End of variables declaration//GEN-END:variables
}
